name: mol_phy_course
channels:
  - conda-forge

dependencies:
  # Core
  - python=3.11
  - pip

  # Jupyter
  - jupyterlab
  - ipykernel

  # Scientific Python
  - numpy
  - scipy
  - pandas
  - matplotlib

  # Bioinformatics (Python)
  - biopython
  - scikit-bio

  # Utilities
  - tqdm
  - click

  # PyTorch
  - pytorch
